### ISSUE TITLE
Building the AST sometimes fails, throwing an exception

### ISSUE THREAD

**Issue by alcuadrado** [federicobond/solidity-parser-antlr#28]
I'm afraid I don't know how to fix this issue, so no PR this time :(

Some invalid sources make the parser fail when building the ast, because [this method throws](https://github.com/federicobond/solidity-parser-antlr/blob/master/src/index.js#L57).

For example, this code `contract { function a() return bool {} }` causes that problem. 

Here's a stack trace of it failing:

```
TypeError: Cannot read property 'getText' of null
    at ASTBuilder.StateVariableDeclaration (node_modules/solidity-parser-antlr/src/ASTBuilder.js:628:23)
    at ASTBuilder.visit (node_modules/solidity-parser-antlr/src/ASTBuilder.js:1133:40)
    at ASTBuilder.ContractPart (node_modules/solidity-parser-antlr/src/ASTBuilder.js:89:17)
    at ASTBuilder.visit (node_modules/solidity-parser-antlr/src/ASTBuilder.js:1133:40)
    at ASTBuilder.<anonymous> (node_modules/solidity-parser-antlr/src/ASTBuilder.js:1121:19)
    at Array.map (<anonymous>)
    at ASTBuilder.visit (node_modules/solidity-parser-antlr/src/ASTBuilder.js:1120:16)
    at ASTBuilder.ContractDefinition (node_modules/solidity-parser-antlr/src/ASTBuilder.js:76:22)
    at ASTBuilder.visit (node_modules/solidity-parser-antlr/src/ASTBuilder.js:1133:40)
    at ASTBuilder.<anonymous> (node_modules/solidity-parser-antlr/src/ASTBuilder.js:1121:19)
    at Array.map (<anonymous>)
    at ASTBuilder.visit (node_modules/solidity-parser-antlr/src/ASTBuilder.js:1120:16)
    at ASTBuilder.SourceUnit (node_modules/solidity-parser-antlr/src/ASTBuilder.js:33:22)
    at ASTBuilder.visit (node_modules/solidity-parser-antlr/src/ASTBuilder.js:1133:40)
    at Object.parse (node_modules/solidity-parser-antlr/src/index.js:65:23)
    at getImports (src/solidity/imports.js:5:22)
    at Context.it (test/solidity/imports.js:15:21)
```

**Comment by federicobond** [comment]
Yes, this is the unfortunate result of trying to build an AST using tolerant mode. If the toleration extends beyond simple things like missing a semicolon into full parts of the tree missing (like the identifier with the contract name in this case) then we have to guard against that everywhere.

We should check if this is only a problem in the places where we are accessing getText() or requires a much bigger refactoring to handle every possible subnode not existing.

**Comment by alcuadrado** [comment]
Thanks for the quick answer and fix fede 🙌🏻
